name: Deploy to GitHub Pages and Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install dependencies and build
      run: |
        npm i
        npm run build

    - name: Deploy to GitHub Pages
      uses: actions/checkout@v2
      with:
        path: 'ring'  
    - name: Deploy to GitHub Pages
      id: github-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: ring  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: ring  
